name: ASP.NET CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: 03-app-dotnet
        
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 1.2.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build the application
      run: dotnet build

    - name: Run tests
      run: dotnet test

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 1.2.x

    - name: Publish the application
      run: dotnet publish -c Release -o ./publish



